name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
      
    - name: Install dependencies
      run: make install
      
    - name: Run tests
      run: make test
      
    - name: Run formatting
      run: make style
