name: Python Ubuntu CI

on:
  push:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
      
#     - name: Install dependencies
#       run: make install
      
#     - name: Run tests
#       run: make test
      
#     - name: Run formatting
#       run: make style

    - name: Merge to main branch
      uses: devmasx/merge-branch@1.4.0
      with:
        target_branch: main
        from_branch: beta
        github_token: $\{{ secrets.GITHUB_TOKEN }}

#     - name: GitHub Push
#       uses: ad-m/github-push-action@v0.6.0
#       with:
#         github_token: $\{{ secrets.GITHUB_TOKEN }}
#         branch: main
